---
title: "Project Title"
author: "Team Name"
date: "01/10/2021"
output:
  pdf_document: default
  html_document: default
---

Project final report should be written in `R Markdown`. It can be in .`pdf` output or `.html` output. 
There is no restriction on the output format since the final report may involve interactive plots etc. 
The final report should be at most 30-pages long. 
All team members should be involved in the preparation of the project final report. 
Project final reports should present appropriate details on the following topics 
(please note that other than Title, Team members, and Conclusion sections, order does not need to necessarily be in the order seen below):

*	Project title page (including project title and team members)
*	Project Description
  * Project goal & social problem addressed
  * Project data & access to data
*	Actions taken (data importing, cleaning, reshaping, exploring, visualizing etc) along with results
*	Results and Discussion
*	Conclusion
* Please provide url address of your project deployed at `GitHub` pages under [GitHub Classroom of MAT381E organization](https://github.com/MAT381E) in Conclusion. 
* The address should be similar to this: https://github.com/MAT381E-Fall21/final-project_teamname (you have make your repo public first).
*	References


Project final report should be prepared collaboratively. 

**Cautionary notes**: 
1) Project final reports will not be accepted after deadline. 
2) You should download `R Project` on `GitHub` to your local computer, do the changes as needed, delete all the files you have not used to produce your report, and finally commit and push all the required files (including `.Rmd` files) just before
your oral presentation (January 29, 2022 or January 30, 2022) via [GitHub Classroom of MAT381E organization](https://github.com/MAT381E).

